pipeline:
  build:
    image: metwork/mfcom-${OS_VERSION}-buildimage:integration
    commands:
      - /opt/metwork-mfext/bin/mfext_wrapper -- python setup.py install
      - /opt/metwork-mfext/bin/mfext_wrapper -- pip install -r dev-requirements.txt
      - /opt/metwork-mfext/bin/mfext_wrapper -- pytest
matrix:
  OS_VERSION:
    - centos6
    - centos7
